apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: feature-flags
  namespace: platform
  labels:
    app: feature-flags
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: feature-flags
