apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secrets
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: auth-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: platform/auth
    - extract:
        key: platform/auth-twilio
