apiVersion: v1
kind: Service
metadata:
  name: auth-stable
  namespace: platform
  labels:
    app: auth
    rollout: stable
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: auth-canary
  namespace: platform
  labels:
    app: auth
    rollout: canary
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 9092
      targetPort: 9092
