apiVersion: v1
kind: Service
metadata:
  name: control-plane-stable
  namespace: platform
  labels:
    app: control-plane
spec:
  selector:
    app: control-plane
  ports:
    - name: http
      port: 9095
      targetPort: 9093
      protocol: TCP
    - name: grpc
      port: 8093
      targetPort: 8093
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane-canary
  namespace: platform
  labels:
    app: control-plane
spec:
  selector:
    app: control-plane
  ports:
    - name: http
      port: 9095
      targetPort: 9093
      protocol: TCP
    - name: grpc
      port: 8093
      targetPort: 8093
      protocol: TCP
  type: ClusterIP
