apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data-quality-tls
  namespace: platform
  labels:
    app: data-quality
    app.kubernetes.io/name: data-quality-tls
    app.kubernetes.io/component: pki
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: youtuop-platform
spec:
  secretName: data-quality-tls-secret
  duration: 2160h
  renewBefore: 720h
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - data-quality
    - data-quality.platform
    - data-quality.platform.svc
    - data-quality.platform.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: platform-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
