apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: processing
  namespace: platform
  labels:
    app: processing
spec:
  # minAvailable=1 مع replicas=2 يضمن إن الـ processing ما توقفش خالص
  # أثناء node maintenance أو rolling update
  minAvailable: 0
  selector:
    matchLabels:
      app: processing
