apiVersion: v1
kind: Service
metadata:
  name: processing-stable
  namespace: platform
  labels:
    app: processing
spec:
  selector:
    app: processing
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: processing-canary
  namespace: platform
  labels:
    app: processing
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
