apiVersion: v1
kind: Service
metadata:
  name: ingestion-stable
  namespace: platform
  labels:
    app: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-canary
  namespace: platform
  labels:
    app: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
