apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notifications
  namespace: platform
  labels:
    app: notifications
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: notifications
