apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs
  namespace: platform
  labels:
    app: jobs
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs
  namespace: platform
  labels:
    app: jobs
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["jobs-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs
  namespace: platform
  labels:
    app: jobs
subjects:
  - kind: ServiceAccount
    name: jobs
    namespace: platform
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: jobs
