apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ml-engine
  namespace: platform
  labels:
    app: ml-engine
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: ml-engine
