apiVersion: v1
kind: Service
metadata:
  name: ml-engine-stable
  namespace: platform
  labels:
    app: ml-engine
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: ml-engine
  ports:
    - name: http
      port: 9098
      targetPort: 9098
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ml-engine-canary
  namespace: platform
  labels:
    app: ml-engine
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: ml-engine
  ports:
    - name: http
      port: 9098
      targetPort: 9098
      protocol: TCP
  type: ClusterIP
