apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-engine
  namespace: platform
  labels:
    app: ml-engine
  annotations:
    # IRSA — للوصول لـ S3 بسبب model artifacts
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/platform-ml-engine"
automountServiceAccountToken: true
