apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: search
  namespace: platform
spec:
  scaleTargetRef:
    name: search
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://victoria-metrics.monitoring.svc.cluster.local:8428
        metricName: search_requests_per_second
        query: sum(rate(search_http_requests_total[2m]))
        threshold: "50"
