apiVersion: v1
kind: Service
metadata:
  name: developer-portal-stable
  namespace: platform
  labels:
    app: developer-portal
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: developer-portal
  ports:
    - name: http
      port: 9097
      targetPort: 9097
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: developer-portal-canary
  namespace: platform
  labels:
    app: developer-portal
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  selector:
    app: developer-portal
  ports:
    - name: http
      port: 9097
      targetPort: 9097
      protocol: TCP
  type: ClusterIP
