apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hydration-tls
  namespace: platform
  labels:
    app: hydration
    app.kubernetes.io/name: hydration-tls
    app.kubernetes.io/component: pki
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: youtuop-platform
spec:
  secretName: hydration-tls-secret
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    size: 256
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - hydration
    - hydration.platform
    - hydration.platform.svc
    - hydration.platform.svc.cluster.local
    - hydration-stable
    - hydration-stable.platform
    - hydration-stable.platform.svc
    - hydration-stable.platform.svc.cluster.local
    - hydration-canary
    - hydration-canary.platform
    - hydration-canary.platform.svc
    - hydration-canary.platform.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: platform-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
