apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-class.yaml
  - gateway.yaml
  - grpc-route-ingestion.yaml
  - grpc-route-processing.yaml
  - http-route-health.yaml
  - http-route-auth.yaml
  - http-route-billing.yaml
  - http-route-notifications.yaml
  - http-route-developer-portal.yaml
  - http-route-realtime.yaml
  - http-route-search.yaml
  - security-policy-jwt.yaml
  - security-policy-admin.yaml
  - security-policy-search.yaml
