apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - ../../../base/notifications

images:
  - name: ghcr.io/scorpiontrader16-ai/youtuop-1/notifications
    newTag: "0.1.0"

commonLabels:
  environment: production
  app.kubernetes.io/managed-by: kustomize
