apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - namespace-deny-all.yaml
  - ingestion
  - auth
  - billing
  - notifications
  - control-plane
  - feature-flags
  - developer-portal
  - ml-engine
  - realtime
  - search
  - analytics
  - processing
  - hydration
  - cilium
  - chaos
  - external-secrets
  - cert-manager
  - monitoring
  - vault
  - api-gateway
  - sync
  - kyverno
  - velero
