name: Generate buf.lock

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-lock:
    name: Generate buf.lock
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Setup buf
        uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99  # v1
        with:
          version: '1.32.2'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate buf.lock
        working-directory: proto
        run: buf dep update

      - name: Commit buf.lock
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403  # v5
        with:
          commit_message: "chore: generate proto/buf.lock"
          file_pattern: proto/buf.lock
